// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUvV4YaUUhNXzHb3WbkaGuoMozo4vdYgw',
    appId: '1:221991252624:web:8a9b2d8ee16c2513891e15',
    messagingSenderId: '221991252624',
    projectId: 'instagram-clone-app-d328d',
    authDomain: 'instagram-clone-app-d328d.firebaseapp.com',
    storageBucket: 'instagram-clone-app-d328d.firebasestorage.app',
    measurementId: 'G-KS3H68CM5K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCN9MkDD7kQB8AA4o_7kxj452vkfyHVfp8',
    appId: '1:221991252624:android:592afff75b6dcc03891e15',
    messagingSenderId: '221991252624',
    projectId: 'instagram-clone-app-d328d',
    storageBucket: 'instagram-clone-app-d328d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXi9IvamdVf6ZXSSveR_NyK3IusQrDiUs',
    appId: '1:221991252624:ios:df485b9152099fb6891e15',
    messagingSenderId: '221991252624',
    projectId: 'instagram-clone-app-d328d',
    storageBucket: 'instagram-clone-app-d328d.firebasestorage.app',
    iosBundleId: 'com.example.instagramDuplicateApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXi9IvamdVf6ZXSSveR_NyK3IusQrDiUs',
    appId: '1:221991252624:ios:df485b9152099fb6891e15',
    messagingSenderId: '221991252624',
    projectId: 'instagram-clone-app-d328d',
    storageBucket: 'instagram-clone-app-d328d.firebasestorage.app',
    iosBundleId: 'com.example.instagramDuplicateApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUvV4YaUUhNXzHb3WbkaGuoMozo4vdYgw',
    appId: '1:221991252624:web:b47afcbecb631461891e15',
    messagingSenderId: '221991252624',
    projectId: 'instagram-clone-app-d328d',
    authDomain: 'instagram-clone-app-d328d.firebaseapp.com',
    storageBucket: 'instagram-clone-app-d328d.firebasestorage.app',
    measurementId: 'G-9ZK05X4T6N',
  );
}
